import React from "react";
import Cake from "../assets/icons/birthday-cake-celebration-svgrepo-com.svg";
import Suitcase from "../assets/icons/suitcase-svgrepo-com.svg";
import Graduation from "../assets/icons/graduation-cap-svgrepo-com.svg";

const HISTORY = [
	{
		year: "2023",
		events: [
			{
				title: "Looking for a new opportunity... 🙏",
				details: "Seeking a new opportunity to further grow as a developer!",
				date: "TBD",
				icon: Suitcase,
				bg: "#e3e3e3",
			},
		],
	},
	{
		year: "2022",
		events: [
			{
				title: "I'm a Software Developer!",
				details:
					"Transitioned to the role as a software developer, taking leadership of a full-stack application that serves as presentation layer for data generated by one of our services",
				date: "Jan 1, 2022",
				icon: Suitcase,
				bg: "#e3e3e3",
			},
		],
	},
	{
		year: "2021",
		events: [
			{
				title: "Intership as a Software Developer",
				details:
					"Joined Tradelegs as an intern where I familiarized myself with server side programming with Ruby using Ruby on Rails ",
				date: "Nov 1, 2021",
				icon: Suitcase,
				bg: "#e3e3e3",
			},
			{
				title: "First generation college graduate!",
				details: "Magna Cum Laude graduate from Hunter College with a B.A in Computer Science and minor in Mathematics",
				date: "May 25, 2021",
				icon: Graduation,
				bg: "#daebfb",
			},
		],
	},
	{
		year: "1999",
		events: [
			{
				title: "Day of Birth",
				details: "Born on the 9th of December 1999!",
				date: "Dec 9, 1999",
				icon: Cake,
				bg: "#ffebeb",
			},
		],
	},
];

const YearCard = ({ year, events }) => {
	return (
		<div className="[&:not(:first-child)]:mt-[1.4em]">
			<div className="grid grid-cols-[auto,1fr] gap-x-[.85em] grid-flow-row">
				{/* empty gap */}
				<div></div>
				{/* year */}
				<div className="flex items-center gap-[1em] mb-[1.35em]">
					<h3 className="text-[1.6em] font-bold">{year}</h3>
					<div className="grow h-[1px] bg-gray-100"></div>
				</div>
				{events.map((event, i) => (
					<React.Fragment key={i}>
						{/* pinpoint */}
						<div className="flex flex-col gap-[.35rem] items-center">
							<div style={{ backgroundColor: event.bg }} className="p-[.55em] rounded-full">
								<img className="max-w-[1.55em]" src={event.icon} alt="" />
							</div>
							<div className="pb-[2.5em] mb-[.35rem] w-[1px] h-full bg-gray-100"></div>
						</div>
						{/* event details */}
						<div className="flex flex-col mb-[1.3em]">
							<b className="block text-[1.175em]">{event.title}</b>
							<span className="inline-block mt-[.1em] text-[.925em] text-gray-400">{event.date}</span>
							<p className="mt-[.5em] tracking-wide leading-[1.25rem] text-[.95em] text-gray-100">{event.details}</p>
						</div>
					</React.Fragment>
				))}
			</div>
		</div>
	);
};
const About = () => {
	return (
		<section className="bg-asif">
			<div className="container pb-[3rem] text-white text-[1rem]">
				<div>
					<h3 className="pt-[1.25em] text-[1.8em] md:text-[clamp(2rem,_3vw,_2.3rem)] font-medium tracking-tight">
						About me 👨‍💻
					</h3>
					<ul className="flex flex-col gap-[.5em] mt-[1em] list-disc list-inside text-gray-200">
						<li>
							I'm a software engineer with a focus on Front-end web development with React but am keen on gaining
							exposure to all layers of the stack.
						</li>
						<li>Besides programming, I enjoy playing video games and watching 🏀 🏈.</li>
					</ul>
				</div>
				<div>
					{HISTORY.map((year, i) => (
						<YearCard {...year} key={i} />
					))}
				</div>
			</div>
		</section>
	);
};

export default About;
